version: '3.8'

services:
  db:
    build: .
    container_name: postgres_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=conecta_presenca
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: always

volumes:
  postgres_data:
