# Generated by Django 6.0.4 on 2026-04-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id_chamada', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.BooleanField()),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chamada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
    ]
